server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ssm?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  #redis缓存
  cache:
    type: redis
    redis:
      time-to-live:             #缓存超时时间
      cache-null-values: false #是否缓存空值
  redis:
    host: localhost
    port: 6379
    password:
  #版本配置
  profiles:
    active:
---
#开发版本
server:
  port: 81
spring:
  profiles: dev
---
#生产版本
server:
  port: 82
spring:
  profiles: pro